---
functional: 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары  
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может из корзины оформить заказ с переходом на страницу оплаты.
  - Сайт должен быть доступен на различных устройствах
  - Корзина хранится в сессии браузера.
non-functional:
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Сайт должен быть SPA приложением
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
